spring:
    application:
        name: eureka-server
    boot:
        admin:
            context-path: /admin
    cloud:
        stream:
            bindings:
                renewChannel:
                    destination: streamNodeRenewTopic
                    content-type: application/json
                registerChannel:
                    destination: streamNodeRegisterTopic
                    content-type: application/json
                unregisterChannel:
                    destination: streamNodeUnRegisterTopic
                    content-type: application/json
            binders:
                kafka1:
                    type: kafka
                    environment:
                        spring:
                            cloud:
                                stream:
                                    kafka:
                                        binder:
                                            brokers: localhost:9092
                                            configuration.sasl.jaas.config: "org.apache.kafka.common.security.scram.ScramLoginModule required username=\"admin\" password=\"admin-secret\";"
            kafka:
                binder:
                    configuration:
                        security.protocol: SASL_PLAINTEXT
                        sasl.mechanism: SCRAM-SHA-256
                    zkNodes: kafka
                    brokers:
                        - kafka:9092


redis:
    server: ostock-redis.ymengq.0001.use1.cache.amazonaws.com
    port: 6379

server:
    port: 8070
eureka:
    instance:
        hostname: eurekaserver
    client:
        registerWithEureka: false
        fetchRegistry: false
        serviceUrl:
            defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    server:
        waitTimeInMsWhenSyncEmpty: 5


management:
    endpoints:
        web:
            exposure:
                include: "*"
   
